package com.joshua.onlinebank.domain;
// Generated 2017-4-8 12:47:57 by Hibernate Tools 3.5.0.Final

/**
 * Personinfo generated by hbm2java
 */
public class Personinfo implements java.io.Serializable {

	private Integer id;
	private Account account;
	private String realname;
	private int age;
	private String sex;
	private String cardid;
	private String address;
	private String telephone;

	public Personinfo() {
	}

	public Personinfo(Account account, String realname, int age, String sex, String cardid, String address,
			String telephone) {
		this.account = account;
		this.realname = realname;
		this.age = age;
		this.sex = sex;
		this.cardid = cardid;
		this.address = address;
		this.telephone = telephone;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getCardid() {
		return this.cardid;
	}

	public void setCardid(String cardid) {
		this.cardid = cardid;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

}
