package com.joshua.onlinebank.domain;
// Generated 2017-4-8 12:47:57 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Transactiontype generated by hbm2java
 */
public class Transactiontype implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set transactionlogs = new HashSet(0);

	public Transactiontype() {
	}

	public Transactiontype(String name) {
		this.name = name;
	}

	public Transactiontype(String name, Set transactionlogs) {
		this.name = name;
		this.transactionlogs = transactionlogs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getTransactionlogs() {
		return this.transactionlogs;
	}

	public void setTransactionlogs(Set transactionlogs) {
		this.transactionlogs = transactionlogs;
	}

}
