package com.joshua.onlinebank.domain;
// Generated 2017-4-8 12:47:57 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Transactionlog generated by hbm2java
 */
public class Transactionlog implements java.io.Serializable {

	private Integer id;
	private Transactiontype transactiontype;
	private Account accountByFromid;
	private Integer toid;

	public Integer getToid() {
		return toid;
	}

	public void setToid(Integer toid) {
		this.toid = toid;
	}

	private double trMoney;
	private Date datetime;

	public Transactionlog() {
	}

	public Transactionlog(Transactiontype transactiontype, Account accountByFromid, Integer toid, double trMoney,
			Date datetime) {
		this.transactiontype = transactiontype;
		this.accountByFromid = accountByFromid;
		this.toid = toid;
		this.trMoney = trMoney;
		this.datetime = datetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Transactiontype getTransactiontype() {
		return this.transactiontype;
	}

	public void setTransactiontype(Transactiontype transactiontype) {
		this.transactiontype = transactiontype;
	}

	public Account getAccountByFromid() {
		return this.accountByFromid;
	}

	public void setAccountByFromid(Account accountByFromid) {
		this.accountByFromid = accountByFromid;
	}

	public double getTrMoney() {
		return this.trMoney;
	}

	public void setTrMoney(double trMoney) {
		this.trMoney = trMoney;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

}
